FROM node:20-alpine

RUN apk add --no-cache libc6-compat curl

WORKDIR /app

COPY package.json yarn.lock ./
RUN yarn config set network-timeout 300000
RUN yarn install --frozen-lockfile

EXPOSE 3000

CMD ["sh", "-c", "rm -rf dist && yarn start:dev"]